def islist(n):
    l=list(map(int,input().split()))
    print(l)
    print(max(l))
    print(min(l))
    print(len(l))
    print(sum(l))
    print(l.pop())
    print(l.append(88))
    print(l.count(7))
n=int(input(""))
islist(n)
